### ISSUE TITLE
Missing sqlalchemy-serializer in Pipfile

### ISSUE THREAD

**Issue by developerjaym** [learn-co-curriculum/python-p4-flask-restful-cr-lab#3]
### Canvas Link

https://learning.flatironschool.com/courses/6182/assignments/209743?module_item_id=483942

### Concern

I ran 'flask run' per the instructions in the readme.
The terminal printed this error

```
python-p4-flask-restful-cr-lab-main/server/models.py", line 2, in <module>
    from sqlalchemy_serializer import SerializerMixin
ModuleNotFoundError: No module named 'sqlalchemy_serializer'
```

I think the pipfile was missing the sqlalchemy_serializer package.

**Comment by professor-ben** [comment]
Thanks! I just most of the Pipfiles in phase 4 and accidentally installed a completely separate package, Flask-Serializer. The mistake has been remedied and the lockfile updated as well.

-Ben
