### ISSUE TITLE
Had to re-run db init

### ISSUE THREAD

**Issue by Matt-Eva** [learn-co-curriculum/python-p4-flask-restful-cr-lab#4]
### Canvas Link

https://learning.flatironschool.com/courses/6182/assignments/209743?module_item_id=483942

### Concern

When I tried running my migration for this lab using `flask db revision --autogenerate`, I kept getting an `ImportError: can't find Python file migrations/env.py`. The only thing within the migrations folder was the versions folder (which was empty), and the .gitignore. I tried running `flask db init`, but had to remove the migrations folder first in order to do so successfully. Once I did that, I was able to create and run my migration fine. Not sure if this is something to do with the lab setup, but it may be an issue students run into as well?

**Comment by TylerTaylor** [comment]
I ran into this as well, and Matt's suggestion worked for me

**Comment by professor-ben** [comment]
This was an issue with a .gitignore file. I'm pushing up a change with an initial migration that should be ready for `flask db upgrade head`.
