### ISSUE TITLE
test only works with .get_json

### ISSUE THREAD

**Issue by Matt-Eva** [learn-co-curriculum/python-p4-flask-restful-cr-lab#5]
### Canvas Link

https://learning.flatironschool.com/courses/6182/assignments/209743?module_item_id=483942

### Concern

The test will only pass if we use the `.get_json()` method in our post route. Should we tell students to default to using that? Is that how they'll basically always handle requests that come from a frontend? I had a similar question about this in a previous reading but I wanted to bring it up here, since this might delay students quite a bit since a lot of our examples use `request.form`.

**Comment by ritchey0713** [comment]
I feel like it got mentioned somewhere as a footnote, but i agree with this, maybe at least putting little reminders in the code alongs?

**Comment by professor-ben** [comment]
`get_json` is definitely mentioned in certain lessons in Phase 4, but I'm never against adding more reminders! I'll put one into this lesson and push it up.

-Ben

**Comment by Matt-Eva** [comment]
Hey Ben! The only place I could find it mentioned was the <a href="https://learning.flatironschool.com/courses/6182/assignments/208456?module_item_id=480488">Chatterbox lab</a>. Almost all of our other examples use `request.form`, including the reading that immediately precedes this lab - <a href="https://learning.flatironschool.com/courses/6182/assignments/209740?module_item_id=483941">Create and Retrieve with Flask Restful</a>. And the chatterbox lab even states that using `.form` is the approach we'll typically take. But I do think that a reminder to use `.get_json` will definitely do the trick here, and will save students a lot of time.
