### ISSUE TITLE
npm start failing

### ISSUE THREAD

**Issue by schnyle** [learn-co-curriculum/python-p4-flask-restful-cr-lab#6]
### Canvas Link

https://learning.flatironschool.com/courses/6259/assignments/233475?module_item_id=547406

### Concern

Running `npm start --prefix client` returned '...bad option: --openssl-legacy-provider'.

Looking online I found a solution to change 
```  
"scripts": {
    "build": "react-scripts --openssl-legacy-provider build",
    "start": "react-scripts --openssl-legacy-provider start"
  }
```
in clients/package.json to
  ```
scripts": {
    "build": "react-scripts build --openssl-legacy-provider",
    "start": "react-scripts start --openssl-legacy-provider"
  }
```

Now `npm start` works for me.
Reference: https://github.com/coreui/coreui-free-react-admin-template/issues/336

**Comment by lizbur10** [comment]
Hi there! Thanks for bringing this to our attention - the error has now been fixed 💙
